package com.example.libraryproject.Models;

public enum BStatus {

    ZREALIZOWANE_ELEKTRONICZNIE,
    ZREALIZOWANE_FIZYCZNE,

    OCZEKIWANIE_ZWROTU,
    WYPOZYCZENIE_ELEKTRONICZNE,
    ANULOWANE,
    WYPOZYCZENIE_FIZYCZNE,
}
